# Generated by Django 5.0.3 on 2024-03-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='image')),
                ('alt', models.CharField(max_length=200)),
                ('href', models.URLField()),
                ('types', models.CharField(max_length=200)),
            ],
        ),
    ]
