# Generated by Django 5.0.3 on 2024-04-02 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsYugoffBlog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
