# Generated by Django 5.0.3 on 2024-05-14 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsYugoffBlog', '0002_delete_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skillsitem',
            options={'ordering': ('skills',), 'verbose_name': 'skill', 'verbose_name_plural': 'skills'},
        ),
    ]
