# Generated by Django 5.0.3 on 2024-03-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsYugoffBlog', '0002_alter_portfolioitem_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
