# Generated by Django 5.0.3 on 2024-03-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsYugoffBlog', '0003_skillsitem_alter_portfolioitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
